test_format = 1.0

[default]

	# ------------
    # Tests to run
    # ------------

	exclude = ["change_url"]

	# -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.5a29828affa68a6e147869bc59331e42d29c95c1.name = "Upgrade from 6.4.1~ynh1"
